# Neal's funnel: v ~ N(0, 3^2), x | v ~ N(0, e^v). Config of the Lip-KL-GPA pre-training.
---
# Data
N_samples_Q: 5000
N_samples_P: 5000
N_dim: 2
dataset: Learning_Neal_funnel
random_seed: 0

N_latent_dim: null
sample_latent: False
N_project_dim: null

beta: null
sigma_P: 1.0
sigma_Q: null
nu: null
interval_length: null
label: null
pts_P: null
pts_Q: null
pts_P_2: null
pts_Q_2: null
y0: null

# (f, Gamma)-divergence
f: KL
alpha: null
formulation: DV
Gamma: Lipschitz
L: 1.0
reverse: False
constraint: hard
lamda: null
phi_model: GPA_NN

# Wasserstein-1 metric
calc_Wasserstein1: False

# Neural Network discriminator
NN_model: fnn
N_fnn_layers:
    - 32
    - 32
    - 32
N_cnn_layers: null
activation_ftn:
    - relu
eps: 0.5
N_conditions: 1

# Discriminator training
epochs_phi: 3
lr_phi: 0.005
optimizer: adam

# Particle transport
epochs: 4000
lr_P: 0.5
ode_solver: forward_euler
mobility: null
lr_P_decay: null

exp_no: pretrain
mb_size_P: 5000
mb_size_Q: 5000

# save/display
save_iter: 50
plot_result: True
plot_intermediate_result: False
...
